### ISSUE TITLE
Translate Initial 

### ISSUE THREAD

**Issue by mariohmol** [ramalabs/brigadistas#14]
Translate our texts in English and Spanish.

Take this file:

https://github.com/mariohmol/brigadistas/blob/master/brigadistacivil/src/assets/i18n/pt.json

And update this 2:

https://github.com/mariohmol/brigadistas/blob/master/brigadistacivil/src/assets/i18n/en.json
https://github.com/mariohmol/brigadistas/blob/master/brigadistacivil/src/assets/i18n/es.json

**Comment by kuwood** [comment]
Re opening issue because we need to add missing keys to en and es translations.
